import { Link } from 'react-router-dom'

const FOOTER_COLS = [
  {
    heading: 'Explore',
    links: [
      { label: 'Bird Species', path: '/bird-species' },
      { label: 'Migration', path: '/migration' },
      { label: 'Monitoring Programs', path: '/monitoring' },
      { label: 'Conservation', path: '/conservation' },
    ],
  },
  {
    heading: 'Resources',
    links: [
      { label: 'Data Explorer', path: '/data-explorer' },
      { label: 'Education & Volunteers', path: '/education' },
      { label: 'Illinois BirdLab', path: '/birdlab' },
    ],
  },
  {
    heading: 'University of Illinois',
    links: [
      { label: 'University of Illinois', path: '#' },
      { label: 'Prairie Research Institute', path: '#' },
      { label: 'Accessibility', path: '#' },
      { label: 'Privacy Policy', path: '#' },
    ],
  },
]

function BlockI() {
  return (
    <svg
      className="block-i"
      width="20"
      height="28"
      viewBox="0 0 20 28"
      aria-hidden="true"
    >
      <rect x="0" y="0" width="20" height="5" />
      <rect x="6" y="5" width="8" height="18" />
      <rect x="0" y="23" width="20" height="5" />
    </svg>
  )
}

export default function Footer() {
  return (
    <footer className="footer">
      <div className="footer__inner">
        <div className="footer__brand">
          <div className="footer__logo">
            <BlockI />
            <div className="footer__logo-text">
              <span className="footer__logo-name">Illinois Bird Explorer</span>
              <span className="footer__logo-sub">University of Illinois</span>
            </div>
          </div>
          <p className="footer__tagline">
            (Placeholder text generated by Claude) Connecting people with the birds of Illinois through science, data, and community engagement.
          </p>
        </div>

        <nav className="footer__nav" aria-label="Footer navigation">
          {FOOTER_COLS.map((col) => (
            <div key={col.heading} className="footer__nav-col">
              <h4 className="footer__nav-heading">{col.heading}</h4>
              <ul>
                {col.links.map((link) => (
                  <li key={link.label}>
                    <Link to={link.path} className="footer__nav-link">
                      {link.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </nav>
      </div>

      <div className="footer__bottom">
        <p>
          © {new Date().getFullYear()} University of Illinois Board of Trustees.{' '}
          (Placeholder text generated by Claude) All rights reserved.
        </p>
      </div>
    </footer>
  )
}
