import PlaceholderPage from './PlaceholderPage'

export default function BirdSpeciesPage() {
  return (
    <PlaceholderPage
      title="Bird Species"
      subtitle="(Placeholder text generated by Claude) Detailed profiles, identification guides, and distribution information for birds found across Illinois."
      desc="(Placeholder text generated by Claude) This section will feature comprehensive species accounts for over 400 birds documented in Illinois, including identification tips, habitat associations, seasonal occurrence, range maps, and conservation status. Content coming soon."
    />
  )
}
