import PlaceholderPage from './PlaceholderPage'

export default function BirdLabPage() {
  return (
    <PlaceholderPage
      title="Illinois BirdLab"
      subtitle="(Placeholder text generated by Claude) Field research and scientific inquiry advancing our understanding of Illinois bird populations, ecology, and behavior."
      desc="(Placeholder text generated by Claude) This section will introduce Illinois BirdLab, its research programs, recent findings, and published work. Learn about the scientists and collaborators driving bird research in the state, ongoing field projects, and opportunities to collaborate or support the work. Content coming soon."
    />
  )
}
