import PlaceholderPage from './PlaceholderPage'

export default function ConservationPage() {
  return (
    <PlaceholderPage
      title="Conservation"
      subtitle="(Placeholder text generated by Claude) Understanding and addressing the conservation challenges facing birds and their habitats in Illinois."
      desc="(Placeholder text generated by Claude) This section will cover threatened and endangered bird species in Illinois, ongoing habitat conservation efforts, policy and land management initiatives, and practical ways individuals and organizations can support bird conservation across the state. Content coming soon."
    />
  )
}
