import PlaceholderPage from './PlaceholderPage'

export default function DataExplorerPage() {
  return (
    <PlaceholderPage
      title="Data Explorer"
      subtitle="(Placeholder text generated by Claude) Interactive tools for visualizing bird distribution, population trends, and historical records across Illinois."
      desc="(Placeholder text generated by Claude) This section will provide an interactive map explorer, population trend charts, and access to historical bird observation records collected across Illinois. Users will be able to filter by species, region, season, and time period, and download datasets for further analysis. Content coming soon."
    />
  )
}
