import PlaceholderPage from './PlaceholderPage'

export default function EducationPage() {
  return (
    <PlaceholderPage
      title="Education and Volunteer Opportunities"
      subtitle="(Placeholder text generated by Claude) Resources for birders of all experience levels, plus ways to get involved in bird monitoring and conservation across Illinois."
      desc="(Placeholder text generated by Claude) This section will feature beginner guides to birdwatching, field identification resources, a directory of volunteer monitoring programs, information on school and youth programs, and a calendar of birding events and field trips across Illinois. Content coming soon."
    />
  )
}
