import { Link } from 'react-router-dom'
import heroImg from '../assets/hero.jpg'

const FEATURES = [
  {
    path: '/bird-species',
    label: 'Bird Species',
    heading: '(Placeholder text generated by Claude) Discover Illinois Birds',
    desc: '(Placeholder text generated by Claude) Explore detailed profiles of over 400 bird species documented across Illinois, including identification guides, habitat information, and seasonal range maps.',
    accent: 'var(--blue-mid)',
  },
  {
    path: '/migration',
    label: 'Migration',
    heading: '(Placeholder text generated by Claude) Track Seasonal Movements',
    desc: '(Placeholder text generated by Claude) Follow the remarkable journeys of migratory birds through Illinois, from spring arrivals to fall departures, with route maps and peak timing guides.',
    accent: 'var(--blue-deep)',
  },
  {
    path: '/monitoring',
    label: 'Monitoring Programs',
    heading: '(Placeholder text generated by Claude) Community Science in Action',
    desc: '(Placeholder text generated by Claude) Learn about long-term bird monitoring programs across the state and how citizen science efforts are tracking population changes over decades.',
    accent: 'var(--navy)',
  },
  {
    path: '/conservation',
    label: 'Conservation',
    heading: '(Placeholder text generated by Claude) Protecting Illinois Habitats',
    desc: '(Placeholder text generated by Claude) Understand the conservation challenges facing Illinois birds and explore ongoing efforts to protect the habitats they depend on throughout their life cycles.',
    accent: 'var(--blue-mid)',
  },
  {
    path: '/data-explorer',
    label: 'Data Explorer',
    heading: '(Placeholder text generated by Claude) Explore the Data',
    desc: '(Placeholder text generated by Claude) Access interactive maps, population trend charts, and historical records drawn from decades of bird monitoring data collected across Illinois.',
    accent: 'var(--blue-deep)',
  },
  {
    path: '/education',
    label: 'Education & Volunteers',
    heading: '(Placeholder text generated by Claude) Learn and Get Involved',
    desc: '(Placeholder text generated by Claude) Find resources for new and experienced birders, connect with volunteer monitoring programs, and discover upcoming events and field trips near you.',
    accent: 'var(--navy)',
  },
  {
    path: '/birdlab',
    label: 'Illinois BirdLab',
    heading: '(Placeholder text generated by Claude) Field Research & Discovery',
    desc: "(Placeholder text generated by Claude) Explore the research programs, publications, and team behind Illinois BirdLab — advancing scientific understanding of the state's avian communities.",
    accent: 'var(--orange)',
  },
]

export default function HomePage() {
  return (
    <div className="home">

      {/* ── HERO ── */}
      <section
        className="hero"
        style={{ backgroundImage: `url(${heroImg})` }}
        aria-label="Illinois Bird Explorer hero"
      >
        <div className="hero__noise" aria-hidden="true" />
        <div className="hero__content">
          <span className="hero__label">
            (Placeholder text generated by Claude) State of Illinois
          </span>
          <h1 className="hero__title">
            Illinois Bird<br />Explorer
          </h1>
          <p className="hero__subtitle">
            (Placeholder text generated by Claude) Discover the remarkable diversity of bird life across the Prairie State — from backyard feeders to remote wetlands, all in one place.
          </p>
          <div className="hero__actions">
            <Link to="/bird-species" className="btn btn--primary">
              (Placeholder text generated by Claude) Explore Species
            </Link>
            <Link to="/data-explorer" className="btn btn--outline">
              (Placeholder text generated by Claude) View Data
            </Link>
          </div>
        </div>
      </section>

      {/* ── MISSION ── */}
      <section className="mission" aria-labelledby="mission-heading">
        <div className="mission__inner">
          <span className="mission__kicker">
            (Placeholder text generated by Claude) Our Mission
          </span>
          <h2 id="mission-heading" className="mission__heading">
            (Placeholder text generated by Claude) Connecting People with Illinois Birds
          </h2>
          <blockquote className="mission__quote">
            (Placeholder text generated by Claude) Illinois is home to over 400 species of birds, from year-round residents to spectacular seasonal migrants passing through on their journeys across the continent. This resource brings together scientific data, community observations, and conservation information to help agencies, land managers, researchers, and the public understand and protect the birds of Illinois.
          </blockquote>
        </div>
      </section>

      {/* ── FEATURES ── */}
      <section className="features" aria-labelledby="features-heading">
        <div className="features__inner">
          <h2 id="features-heading" className="features__heading">
            (Placeholder text generated by Claude) Explore the Site
          </h2>
          <p className="features__subheading">
            (Placeholder text generated by Claude) Everything you need to learn about, track, and protect Illinois birds.
          </p>
          <div className="features__grid">
            {FEATURES.map((card) => (
              <Link to={card.path} key={card.path} className="feature-card">
                <div
                  className="feature-card__accent"
                  style={{ background: card.accent }}
                  aria-hidden="true"
                />
                <div className="feature-card__body">
                  <span className="feature-card__label">{card.label}</span>
                  <h3 className="feature-card__heading">{card.heading}</h3>
                  <p className="feature-card__desc">{card.desc}</p>
                  <span className="feature-card__cta">
                    (Placeholder text generated by Claude) Learn more{' '}
                    <span aria-hidden="true">→</span>
                  </span>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>

    </div>
  )
}
