import PlaceholderPage from './PlaceholderPage'

export default function MigrationPage() {
  return (
    <PlaceholderPage
      title="Migration"
      subtitle="(Placeholder text generated by Claude) Explore the seasonal movements of birds through Illinois and learn about the state's role as a critical migratory corridor."
      desc="(Placeholder text generated by Claude) This section will cover spring and fall migration patterns, key migratory routes and flyways passing through Illinois, peak timing for major species groups, and maps of important stopover sites across the state. Content coming soon."
    />
  )
}
