import PlaceholderPage from './PlaceholderPage'

export default function MonitoringPage() {
  return (
    <PlaceholderPage
      title="Monitoring Programs"
      subtitle="(Placeholder text generated by Claude) Long-term bird population monitoring initiatives that track how Illinois birds are faring over time."
      desc="(Placeholder text generated by Claude) This section will highlight ongoing bird monitoring programs in Illinois, including the Breeding Bird Survey, Christmas Bird Count, eBird, and other citizen science initiatives. Learn how these programs collect data and how you can participate. Content coming soon."
    />
  )
}
