export default function PlaceholderPage({ title, subtitle, desc }) {
  return (
    <div className="placeholder-page">
      <div className="placeholder-page__hero">
        <div className="placeholder-page__hero-content">
          <h1 className="placeholder-page__title">{title}</h1>
          <p className="placeholder-page__subtitle">{subtitle}</p>
        </div>
      </div>

      <div className="placeholder-page__body">
        <div className="placeholder-page__inner">
          <div className="placeholder-page__coming-soon">
            <span className="placeholder-page__icon" aria-hidden="true">🔍</span>
            <h2>(Placeholder text generated by Claude) Content Coming Soon</h2>
            <p>{desc}</p>
          </div>
        </div>
      </div>
    </div>
  )
}
